### ISSUE TITLE
Check MetricsCOSEWIC package is working properly

### ISSUE THREAD

**Issue by DylanMG** [Pacific-salmon-assess/COSEWIC-prioritize#9]
I've looked at the documentation on the [MetricsCOSEWIC wiki](https://github.com/SOLV-Code/MetricsCOSEWIC/wiki/2-Probability-of-Decline:-Estimation-Methods), centered the data [here ](https://github.com/Pacific-salmon-assess/COSEWIC-prioritize/blob/main/MetricsCOSEWIC_check.R) and the slopes (i.e. probability of decline) still don't match up with the `lm()` estimates. 
- Am I treating `NA`s right? Do I need to explicitly include them for years within the 3 generation timeframe?
- Is it proper to `group_by()` then scale? This makes sense to keep the mean and variance within a population but I'd be happy to have a discussion about it. I suppose its all about how one imagines partitioning variance within/among stocks.

**Comment by brendanmichaelconnors** [comment]
I've taken a look and compared OLS lm() based estimates of percent change over most recent three generations with Bayesian lm ones using jags via the MetricsCOSEWIC package. 

Code is [here](https://github.com/Pacific-salmon-assess/COSEWIC-prioritize/blob/main/bays_per_change.R). In a nutshell I scaled the data (within DUs) and added back in NAs for years between the first and last observations without data. 

Estimates are generally in the same direction and magnitude but definitely not lining up tightly, need to explore more to diagnose why. For now will keep simple OLS lm() based estimates of % change in summary doc.

**Comment by carrieholt** [comment]
This may be related to the sensitivity to priors that Gottfried noticed for Fraser sockeye DUs. We are investigating this in the Decline Metrics working group.

**Comment by DylanMG** [comment]
Close for now and follow up with new [Stan ](https://github.com/carrieholt/MetricsCOSEWIC-Stan)version in development.
